version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOSTNAME=localhost
    ports:
      - 8080:8080
    depends_on:
      - redis
  redis:
    image: redis:latest
